[workspace]

members = [
    "1_sonar_sweep",
    "2_dive",
    "3_binary_diagnostic",
    "4_giant_squid",
    "5_hydrothermal_venture",
    "6_lanternfish",
    "7_the_treachery_of_whales",
    "8_seven_segment_search",
    "9_smoke_basin",
    "10_syntax_scoring"
]